######################################################################
# Automatically generated by qmake (3.0) mer. juin 13 21:08:30 2018
######################################################################

TEMPLATE = app
TARGET = src_envs
INCLUDEPATH += .

# Input
HEADERS += Environnement.h EnvironnementGui.h
SOURCES += Environnement.cpp EnvironnementGui.cpp main.cpp
