gAgent: gagent::AgentCore Class Reference
gagent::AgentCore Class Reference
#include <AgentCore.hpp>
Static Public Member Functions
static void initAgentSystem ()
Initialize the agent system with proper signal handling.
static void stopAgentSystem ()
static void syncAgentSystem ()
static void initEnvironnementSystem (gagent::Environnement &, bool gui=false, unsigned int timer_val=500)
Detailed Description
Definition at line 27 of file AgentCore.hpp.
Member Function Documentation
initAgentSystem()
void gagent::AgentCore::initAgentSystem () static
Initialize the agent system with proper signal handling.
Sets up signal handlers for SIGINT, SIGTERM, and SIGQUIT to ensure graceful shutdown of all child processes in the process group.
Definition at line 27 of file AgentCore.cpp.
Referenced by main().
initEnvironnementSystem()
void gagent::AgentCore::initEnvironnementSystem (gagent::Environnement & env, bool gui = false, unsigned int timer_val = 500) static
Definition at line 100 of file AgentCore.cpp.
References gagent::Environnement::start().
Referenced by main().
stopAgentSystem()
void gagent::AgentCore::stopAgentSystem () static
Definition at line 60 of file AgentCore.cpp.
Referenced by main().
syncAgentSystem()
void gagent::AgentCore::syncAgentSystem () static
Definition at line 66 of file AgentCore.cpp.
Referenced by main().
The documentation for this class was generated from the following files:
src_agent/AgentCore.hpp
src_agent/AgentCore.cpp