gAgent: gagent::Environnement Class Reference
gagent::Environnement Class Reference
#include <Environnement.hpp>
Public Member Functions
Environnement ()
virtual ~Environnement ()
virtual void start (bool gui, unsigned int timer_val) final
virtual void clear_nsap () final
virtual int push_nsap () final
virtual int pull_nsap () final
virtual std::map< int, std::string > * get_nsaps () final
virtual void init_env ()
virtual void link_attribut ()
virtual void event_loop ()
virtual void link_id (std::string _id) final
virtual void link_name (std::string _name) final
virtual void link_pos_x (std::string _pos_x) final
virtual void link_pos_y (std::string _pos_y) final
virtual void link_color (std::string _color) final
virtual void link_shape (std::string _shape) final
virtual void link_size (std::string _size) final
virtual void link_size_x (std::string _size_x) final
virtual void link_size_y (std::string _size_y) final
virtual void link_size_z (std::string _size_z) final
virtual void link_val (std::string _val) final
virtual void make_agent () final
virtual void readDataFromQueueMsg ()
int sendMsgMonitor (std::string)
Public Attributes
std::string id
std::string name
std::string shape
std::string size
std::string size_x
std::string size_y
std::string size_z
std::string color
std::string pos_x
std::string pos_y
std::string val
std::string pattern
std::vector< std::string > vals
std::vector< gagent::VisualAgent * > list_visual_agents
int map_width = 600
int map_height = 300
Detailed Description
Definition at line 30 of file Environnement.hpp.
Constructor & Destructor Documentation
Environnement()
gagent::Environnement::Environnement ()
Definition at line 14 of file Environnement.cpp.
References color, name, pattern, pos_x, pos_y, size, size_x, size_y, size_z, and val.
~Environnement()
gagent::Environnement::~Environnement () virtual
Definition at line 35 of file Environnement.cpp.
Member Function Documentation
clear_nsap()
void gagent::Environnement::clear_nsap () final virtual
Definition at line 131 of file Environnement.cpp.
event_loop()
virtual void gagent::Environnement::event_loop () inline virtual
Reimplemented in myEnv.
Definition at line 43 of file Environnement.hpp.
Referenced by gagent::EnvironnementGui::refresh().
get_nsaps()
std::map< int, std::string > * gagent::Environnement::get_nsaps () final virtual
Definition at line 158 of file Environnement.cpp.
init_env()
virtual void gagent::Environnement::init_env () inline virtual
Reimplemented in myEnv.
Definition at line 41 of file Environnement.hpp.
link_attribut()
virtual void gagent::Environnement::link_attribut () inline virtual
Reimplemented in myEnv.
Definition at line 42 of file Environnement.hpp.
link_color()
virtual void gagent::Environnement::link_color (std::string _color) inline final virtual
Definition at line 49 of file Environnement.hpp.
References color.
Referenced by myEnv::link_attribut().
link_id()
virtual void gagent::Environnement::link_id (std::string _id) inline final virtual
Definition at line 45 of file Environnement.hpp.
Referenced by myEnv::link_attribut().
link_name()
virtual void gagent::Environnement::link_name (std::string _name) inline final virtual
Definition at line 46 of file Environnement.hpp.
References name.
Referenced by myEnv::link_attribut().
link_pos_x()
virtual void gagent::Environnement::link_pos_x (std::string _pos_x) inline final virtual
Definition at line 47 of file Environnement.hpp.
References pos_x.
Referenced by myEnv::link_attribut().
link_pos_y()
virtual void gagent::Environnement::link_pos_y (std::string _pos_y) inline final virtual
Definition at line 48 of file Environnement.hpp.
References pos_y.
Referenced by myEnv::link_attribut().
link_shape()
virtual void gagent::Environnement::link_shape (std::string _shape) inline final virtual
Definition at line 50 of file Environnement.hpp.
References shape.
Referenced by myEnv::link_attribut().
link_size()
virtual void gagent::Environnement::link_size (std::string _size) inline final virtual
Definition at line 51 of file Environnement.hpp.
References size.
Referenced by myEnv::link_attribut().
link_size_x()
virtual void gagent::Environnement::link_size_x (std::string _size_x) inline final virtual
Definition at line 52 of file Environnement.hpp.
References size_x.
Referenced by myEnv::link_attribut().
link_size_y()
virtual void gagent::Environnement::link_size_y (std::string _size_y) inline final virtual
Definition at line 53 of file Environnement.hpp.
References size_y.
Referenced by myEnv::link_attribut().
link_size_z()
virtual void gagent::Environnement::link_size_z (std::string _size_z) inline final virtual
Definition at line 54 of file Environnement.hpp.
References size_z.
Referenced by myEnv::link_attribut().
link_val()
virtual void gagent::Environnement::link_val (std::string _val) inline final virtual
Definition at line 55 of file Environnement.hpp.
References val.
make_agent()
void gagent::Environnement::make_agent () final virtual
Definition at line 164 of file Environnement.cpp.
References gagent::VisualAgent::color, gagent::VisualAgent::id, gagent::VisualAgent::name, gagent::VisualAgent::pattern, gagent::VisualAgent::pos_x, gagent::VisualAgent::pos_y, gagent::VisualAgent::shape, gagent::VisualAgent::size, gagent::VisualAgent::size_x, gagent::VisualAgent::size_y, gagent::VisualAgent::size_z, gagent::VisualAgent::val, and gagent::VisualAgent::vals.
Referenced by gagent::EnvironnementGui::refresh().
pull_nsap()
int gagent::Environnement::pull_nsap () final virtual
Definition at line 138 of file Environnement.cpp.
push_nsap()
int gagent::Environnement::push_nsap () final virtual
Definition at line 134 of file Environnement.cpp.
readDataFromQueueMsg()
void gagent::Environnement::readDataFromQueueMsg () virtual
Definition at line 39 of file Environnement.cpp.
References gagent::MessageParser::parsekeyValSeq().
Referenced by gagent::EnvironnementGui::createWindow().
sendMsgMonitor()
int gagent::Environnement::sendMsgMonitor (std::string msg)
Definition at line 210 of file Environnement.cpp.
References BUFLEN.
start()
void gagent::Environnement::start (bool gui, unsigned int timer_val) final virtual
Definition at line 142 of file Environnement.cpp.
References gagent::EnvironnementGui::createWindow(), and gagent::EnvironnementGui::setEnvPtr().
Referenced by gagent::AgentCore::initEnvironnementSystem().
Member Data Documentation
color
std::string gagent::Environnement::color
Definition at line 73 of file Environnement.hpp.
Referenced by Environnement(), and link_color().
id
std::string gagent::Environnement::id
Definition at line 66 of file Environnement.hpp.
list_visual_agents
std::vector<gagent::VisualAgent*> gagent::Environnement::list_visual_agents
Definition at line 80 of file Environnement.hpp.
Referenced by gagent::EnvironnementGui::refresh().
map_height
int gagent::Environnement::map_height = 300
Definition at line 83 of file Environnement.hpp.
Referenced by gagent::EnvironnementGui::createWindow(), and gagent::EnvironnementGui::refresh().
map_width
int gagent::Environnement::map_width = 600
Definition at line 82 of file Environnement.hpp.
Referenced by gagent::EnvironnementGui::createWindow(), and gagent::EnvironnementGui::refresh().
name
std::string gagent::Environnement::name
Definition at line 67 of file Environnement.hpp.
Referenced by Environnement(), and link_name().
pattern
std::string gagent::Environnement::pattern
Definition at line 77 of file Environnement.hpp.
Referenced by Environnement().
pos_x
std::string gagent::Environnement::pos_x
Definition at line 74 of file Environnement.hpp.
Referenced by Environnement(), and link_pos_x().
pos_y
std::string gagent::Environnement::pos_y
Definition at line 75 of file Environnement.hpp.
Referenced by Environnement(), and link_pos_y().
shape
std::string gagent::Environnement::shape
Definition at line 68 of file Environnement.hpp.
Referenced by link_shape().
size
std::string gagent::Environnement::size
Definition at line 69 of file Environnement.hpp.
Referenced by Environnement(), and link_size().
size_x
std::string gagent::Environnement::size_x
Definition at line 70 of file Environnement.hpp.
Referenced by Environnement(), and link_size_x().
size_y
std::string gagent::Environnement::size_y
Definition at line 71 of file Environnement.hpp.
Referenced by Environnement(), and link_size_y().
size_z
std::string gagent::Environnement::size_z
Definition at line 72 of file Environnement.hpp.
Referenced by Environnement(), and link_size_z().
val
std::string gagent::Environnement::val
Definition at line 76 of file Environnement.hpp.
Referenced by Environnement(), and link_val().
vals
std::vector<std::string> gagent::Environnement::vals
Definition at line 78 of file Environnement.hpp.
The documentation for this class was generated from the following files:
src_agent/Environnement.hpp
src_agent/Environnement.cpp