gAgent: myAgent Class Reference
myAgent Class Reference
Public Member Functions
myAgent ()
void setup ()
Public Member Functions inherited from gagent::Agent
Agent ()
virtual ~Agent ()
bool is_notification ()
void * scheduler (void *)
void exthread (Behaviour *)
void control_Thread ()
void listener_extern_signals_Thread ()
void control_message ()
void init ()
void _init (int)
virtual void takeDown ()
int doDelete ()
int doActivate ()
int doSuspend ()
int doWait ()
int doWake ()
int doMove ()
int doAction (const int)
void addBehaviour (Behaviour *)
void removeBehaviour (Behaviour *)
AgentID getAgentId ()
int sendMsgMonitor (std::string)
void signal_handler (const boost::system::error_code &error, int signal_number)
void addAttribut (std::string)
void removeAttribut (std::string)
void setAttribut (std::string, std::string)
std::string getAttribut (std::string)
void attributUpdated ()
Additional Inherited Members
Public Attributes inherited from gagent::Agent
int agentStatus
pid_t chldpid
pid_t ppid
Agent * this_agent
Static Public Attributes inherited from gagent::Agent
static const int AGENT_UNKNOWN = 0
static const int AGENT_CREATED = 1
static const int AGENT_INITED = 2
static const int AGENT_ACTIVE = 3
static const int AGENT_SUSPENDED = 4
static const int AGENT_TRANSIT = 5
static const int AGENT_WAITING = 6
static const int AGENT_DELETED = 7
static const int AGENT_WAKING = 8
Detailed Description
Definition at line 56 of file main.cpp.
Constructor & Destructor Documentation
myAgent()
myAgent::myAgent () inline
Definition at line 58 of file main.cpp.
Member Function Documentation
setup()
void myAgent::setup () inline virtual
Implements gagent::Agent.
Definition at line 62 of file main.cpp.
References gagent::Agent::addAttribut(), gagent::Agent::addBehaviour(), gagent::Agent::attributUpdated(), gagent::Agent::setAttribut(), and gagent::Agent::this_agent.
The documentation for this class was generated from the following file:
test_agent/main.cpp