gAgent: gagent::Logger Class Reference
gagent::Logger Class Reference
Thread-safe logger singleton.
#include <Logger.hpp>
Public Member Functions
void setLogLevel (LogLevel level)
Set minimum log level to display.
bool setLogFile (const std::string &filename)
Set output log file.
void log (LogLevel level, const std::string &message, const std::string &source="")
Log a message.
void close ()
Close log file.
void debug (const std::string &msg, const std::string &src="")
void info (const std::string &msg, const std::string &src="")
void warning (const std::string &msg, const std::string &src="")
void error (const std::string &msg, const std::string &src="")
void critical (const std::string &msg, const std::string &src="")
Logger (const Logger &)=delete
Logger & operator= (const Logger &)=delete
Static Public Member Functions
static Logger & getInstance ()
Get singleton instance.
Detailed Description
Thread-safe logger singleton.
Provides centralized logging functionality with multiple severity levels, file output support, and timestamp formatting.
Example usage:
Logger::getInstance().log(LogLevel::INFO, "Agent started", "MyAgent");
Logger::getInstance().setLogFile("agent.log");
Definition at line 44 of file Logger.hpp.
Constructor & Destructor Documentation
Logger()
gagent::Logger::Logger (const Logger &) delete
Member Function Documentation
close()
void gagent::Logger::close () inline
Close log file.
Definition at line 111 of file Logger.hpp.
critical()
void gagent::Logger::critical (const std::string & msg, const std::string & src = "") inline
Definition at line 135 of file Logger.hpp.
References gagent::CRITICAL, and log().
debug()
void gagent::Logger::debug (const std::string & msg, const std::string & src = "") inline
Definition at line 119 of file Logger.hpp.
References gagent::DEBUG, and log().
error()
void gagent::Logger::error (const std::string & msg, const std::string & src = "") inline
Definition at line 131 of file Logger.hpp.
References gagent::ERROR, and log().
Referenced by gagent::ErrorHandler::handleException(), and gagent::ErrorHandler::logSystemError().
getInstance()
static Logger & gagent::Logger::getInstance () inline static
Get singleton instance.
Returns
Reference to the logger instance
Definition at line 50 of file Logger.hpp.
Referenced by gagent::ErrorHandler::handleException(), and gagent::ErrorHandler::logSystemError().
info()
void gagent::Logger::info (const std::string & msg, const std::string & src = "") inline
Definition at line 123 of file Logger.hpp.
References gagent::INFO, and log().
log()
void gagent::Logger::log (LogLevel level, const std::string & message, const std::string & source = "") inline
Log a message.
Parameters
level Severity level
message Message to log
source Source component (optional)
Definition at line 81 of file Logger.hpp.
Referenced by critical(), debug(), error(), info(), and warning().
operator=()
Logger & gagent::Logger::operator= (const Logger &) delete
setLogFile()
bool gagent::Logger::setLogFile (const std::string & filename) inline
Set output log file.
Parameters
filename Path to log file
Returns
true if file opened successfully
Definition at line 69 of file Logger.hpp.
setLogLevel()
void gagent::Logger::setLogLevel (LogLevel level) inline
Set minimum log level to display.
Parameters
level Minimum level to log
Definition at line 59 of file Logger.hpp.
warning()
void gagent::Logger::warning (const std::string & msg, const std::string & src = "") inline
Definition at line 127 of file Logger.hpp.
References log(), and gagent::WARNING.
The documentation for this class was generated from the following file:
src_agent/Logger.hpp