gAgent: gagent::EnvironnementGui Class Reference
gagent::EnvironnementGui Class Reference
#include <EnvironnementGui.hpp>
Public Slots
void refresh ()
Public Member Functions
EnvironnementGui ()
virtual ~EnvironnementGui ()
int createWindow (int argc, char *argv[], bool, unsigned int)
void setColor (int r, int g, int b, int a=255)
bool isGui () const
void setGui (bool gui=false)
void setEnvPtr (gagent::Environnement *_env_ptr)
Detailed Description
Definition at line 39 of file EnvironnementGui.hpp.
Constructor & Destructor Documentation
EnvironnementGui()
gagent::EnvironnementGui::EnvironnementGui ()
Definition at line 12 of file EnvironnementGui.cpp.
~EnvironnementGui()
gagent::EnvironnementGui::~EnvironnementGui () virtual
Definition at line 16 of file EnvironnementGui.cpp.
Member Function Documentation
createWindow()
int gagent::EnvironnementGui::createWindow (int argc, char * argv[], bool gui, unsigned int timer_val)
Definition at line 20 of file EnvironnementGui.cpp.
References Ui_guiWindow::graphicsView, gagent::Environnement::map_height, gagent::Environnement::map_width, gagent::Environnement::readDataFromQueueMsg(), refresh(), and Ui_guiWindow::setupUi().
Referenced by gagent::Environnement::start().
isGui()
bool gagent::EnvironnementGui::isGui () const inline
Definition at line 48 of file EnvironnementGui.hpp.
refresh
void gagent::EnvironnementGui::refresh () slot
Definition at line 44 of file EnvironnementGui.cpp.
References gagent::VisualAgent::color, gagent::Environnement::event_loop(), Ui_guiWindow::graphicsView, gagent::Environnement::list_visual_agents, gagent::Environnement::make_agent(), gagent::Environnement::map_height, gagent::Environnement::map_width, gagent::VisualAgent::pattern, gagent::VisualAgent::pos_x, gagent::VisualAgent::pos_y, gagent::VisualAgent::shape, gagent::VisualAgent::size_x, and gagent::VisualAgent::size_y.
Referenced by createWindow().
setColor()
void gagent::EnvironnementGui::setColor (int r, int g, int b, int a = 255)
setEnvPtr()
void gagent::EnvironnementGui::setEnvPtr (gagent::Environnement * _env_ptr) inline
Definition at line 56 of file EnvironnementGui.hpp.
Referenced by gagent::Environnement::start().
setGui()
void gagent::EnvironnementGui::setGui (bool gui = false) inline
Definition at line 52 of file EnvironnementGui.hpp.
The documentation for this class was generated from the following files:
src_agent/EnvironnementGui.hpp
src_agent/EnvironnementGui.cpp