gAgent: gagent::msgKeyVal::key_value_sequence< Iterator > Struct Template Reference
gagent::msgKeyVal::key_value_sequence< Iterator > Struct Template Reference
Public Member Functions
key_value_sequence ()
Public Attributes
qi::rule< Iterator, std::map< std::string, std::string >()> query
qi::rule< Iterator, std::pair< std::string, std::string >()> pair
qi::rule< Iterator, std::string()> key
qi::rule< Iterator, std::string()> value
Detailed Description
template<typename Iterator>
struct gagent::msgKeyVal::key_value_sequence< Iterator >
Definition at line 18 of file MessageParser.cpp.
Constructor & Destructor Documentation
key_value_sequence()
template<typename Iterator > gagent::msgKeyVal::key_value_sequence< Iterator >::key_value_sequence () inline
Definition at line 21 of file MessageParser.cpp.
References gagent::msgKeyVal::key_value_sequence< Iterator >::key, gagent::msgKeyVal::key_value_sequence< Iterator >::pair, gagent::msgKeyVal::key_value_sequence< Iterator >::query, and gagent::msgKeyVal::key_value_sequence< Iterator >::value.
Member Data Documentation
key
template<typename Iterator > qi::rule<Iterator, std::string()> gagent::msgKeyVal::key_value_sequence< Iterator >::key
Definition at line 32 of file MessageParser.cpp.
Referenced by gagent::msgKeyVal::key_value_sequence< Iterator >::key_value_sequence().
pair
template<typename Iterator > qi::rule<Iterator, std::pair<std::string, std::string>()> gagent::msgKeyVal::key_value_sequence< Iterator >::pair
Definition at line 31 of file MessageParser.cpp.
Referenced by gagent::msgKeyVal::key_value_sequence< Iterator >::key_value_sequence().
query
template<typename Iterator > qi::rule<Iterator, std::map<std::string, std::string>()> gagent::msgKeyVal::key_value_sequence< Iterator >::query
Definition at line 30 of file MessageParser.cpp.
Referenced by gagent::msgKeyVal::key_value_sequence< Iterator >::key_value_sequence().
value
template<typename Iterator > qi::rule<Iterator, std::string()> gagent::msgKeyVal::key_value_sequence< Iterator >::value
Definition at line 32 of file MessageParser.cpp.
Referenced by gagent::msgKeyVal::key_value_sequence< Iterator >::key_value_sequence().
The documentation for this struct was generated from the following file:
src_agent/MessageParser.cpp