gAgent: gagent::Agent Class Reference
gagent::Agent Class Reference abstract
#include <Agent.hpp>
Public Member Functions
Agent ()
virtual ~Agent ()
bool is_notification ()
void * scheduler (void *)
void exthread (Behaviour *)
void control_Thread ()
void listener_extern_signals_Thread ()
void control_message ()
void init ()
void _init (int)
virtual void setup ()=0
virtual void takeDown ()
int doDelete ()
int doActivate ()
int doSuspend ()
int doWait ()
int doWake ()
int doMove ()
int doAction (const int)
void addBehaviour (Behaviour *)
void removeBehaviour (Behaviour *)
AgentID getAgentId ()
int sendMsgMonitor (std::string)
void signal_handler (const boost::system::error_code &error, int signal_number)
void addAttribut (std::string)
void removeAttribut (std::string)
void setAttribut (std::string, std::string)
std::string getAttribut (std::string)
void attributUpdated ()
Public Attributes
int agentStatus
pid_t chldpid
pid_t ppid
Agent * this_agent
Static Public Attributes
static const int AGENT_UNKNOWN = 0
static const int AGENT_CREATED = 1
static const int AGENT_INITED = 2
static const int AGENT_ACTIVE = 3
static const int AGENT_SUSPENDED = 4
static const int AGENT_TRANSIT = 5
static const int AGENT_WAITING = 6
static const int AGENT_DELETED = 7
static const int AGENT_WAKING = 8
Detailed Description
Definition at line 54 of file Agent.hpp.
Constructor & Destructor Documentation
Agent()
gagent::Agent::Agent ()
Definition at line 10 of file Agent.cpp.
References this_agent.
~Agent()
gagent::Agent::~Agent () virtual
Definition at line 14 of file Agent.cpp.
Member Function Documentation
_init()
void gagent::Agent::_init (int dbg)
Definition at line 47 of file Agent.cpp.
References AGENT_INITED, AGENT_UNKNOWN, agentStatus, chldpid, control_message(), control_Thread(), doDelete(), exthread(), listener_extern_signals_Thread(), sendMsgMonitor(), setup(), and takeDown().
Referenced by init().
addAttribut()
void gagent::Agent::addAttribut (std::string attr)
Definition at line 465 of file Agent.cpp.
Referenced by myAgent::setup().
addBehaviour()
void gagent::Agent::addBehaviour (Behaviour * b)
Definition at line 245 of file Agent.cpp.
Referenced by myAgent::setup().
attributUpdated()
void gagent::Agent::attributUpdated ()
Definition at line 428 of file Agent.cpp.
Referenced by myTickerBehaviour::onTick(), and myAgent::setup().
control_message()
void gagent::Agent::control_message ()
Definition at line 207 of file Agent.cpp.
References sendMsgMonitor().
Referenced by _init().
control_Thread()
void gagent::Agent::control_Thread ()
Definition at line 129 of file Agent.cpp.
References AGENT_ACTIVE, AGENT_DELETED, AGENT_SUSPENDED, AGENT_TRANSIT, AGENT_WAITING, and AGENT_WAKING.
Referenced by _init().
doAction()
int gagent::Agent::doAction (const int act)
Definition at line 287 of file Agent.cpp.
References AGENT_ACTIVE, AGENT_DELETED, AGENT_SUSPENDED, AGENT_TRANSIT, AGENT_WAITING, AGENT_WAKING, chldpid, cv, mtx, sendMsgMonitor(), SIG_AGENT_ACTIVE, SIG_AGENT_DELETE, SIG_AGENT_SUSPEND, SIG_AGENT_TRANSIT, SIG_AGENT_WAIT, SIG_AGENT_WAKE, and this_agent.
Referenced by gagent::Behaviour::doAction(), doActivate(), doDelete(), doMove(), doSuspend(), doWait(), doWake(), and signal_handler().
doActivate()
int gagent::Agent::doActivate ()
Definition at line 267 of file Agent.cpp.
References AGENT_ACTIVE, and doAction().
Referenced by gagent::Behaviour::doActivate().
doDelete()
int gagent::Agent::doDelete ()
Definition at line 263 of file Agent.cpp.
References AGENT_DELETED, and doAction().
Referenced by _init(), and gagent::Behaviour::doDelete().
doMove()
int gagent::Agent::doMove ()
Definition at line 283 of file Agent.cpp.
References AGENT_TRANSIT, and doAction().
Referenced by gagent::Behaviour::doMove().
doSuspend()
int gagent::Agent::doSuspend ()
Definition at line 271 of file Agent.cpp.
References AGENT_SUSPENDED, and doAction().
Referenced by gagent::Behaviour::doSuspend().
doWait()
int gagent::Agent::doWait ()
Definition at line 275 of file Agent.cpp.
References AGENT_WAITING, and doAction().
Referenced by gagent::Behaviour::doWait().
doWake()
int gagent::Agent::doWake ()
Definition at line 279 of file Agent.cpp.
References AGENT_WAKING, and doAction().
Referenced by gagent::Behaviour::doWake().
exthread()
void gagent::Agent::exthread (Behaviour * beh)
Definition at line 80 of file Agent.cpp.
References gagent::Behaviour::action(), gagent::Behaviour::done(), gagent::Behaviour::onEnd(), and gagent::Behaviour::onStart().
Referenced by _init().
getAgentId()
AgentID gagent::Agent::getAgentId ()
Definition at line 259 of file Agent.cpp.
getAttribut()
std::string gagent::Agent::getAttribut (std::string attr)
Definition at line 482 of file Agent.cpp.
init()
void gagent::Agent::init ()
Definition at line 18 of file Agent.cpp.
References _init(), chldpid, ppid, and this_agent.
Referenced by main().
is_notification()
bool gagent::Agent::is_notification ()
listener_extern_signals_Thread()
void gagent::Agent::listener_extern_signals_Thread ()
Definition at line 96 of file Agent.cpp.
References SIG_AGENT_ACTIVE, SIG_AGENT_DELETE, SIG_AGENT_SUSPEND, SIG_AGENT_TRANSIT, SIG_AGENT_WAIT, SIG_AGENT_WAKE, signal_handler(), and this_agent.
Referenced by _init().
removeAttribut()
void gagent::Agent::removeAttribut (std::string attr)
Definition at line 469 of file Agent.cpp.
removeBehaviour()
void gagent::Agent::removeBehaviour (Behaviour *)
scheduler()
void * gagent::Agent::scheduler (void *)
sendMsgMonitor()
int gagent::Agent::sendMsgMonitor (std::string msg)
Definition at line 253 of file Agent.cpp.
References BUFLEN, gagent::AgentID::getAgentID(), and udp_client_server::udp_client::send().
Referenced by _init(), control_message(), and doAction().
setAttribut()
void gagent::Agent::setAttribut (std::string attr, std::string val)
Definition at line 473 of file Agent.cpp.
Referenced by myTickerBehaviour::onTick(), and myAgent::setup().
setup()
virtual void gagent::Agent::setup () pure virtual
Implemented in myAgent.
Referenced by _init().
signal_handler()
void gagent::Agent::signal_handler (const boost::system::error_code & error, int signal_number)
Definition at line 403 of file Agent.cpp.
References AGENT_ACTIVE, AGENT_DELETED, AGENT_SUSPENDED, AGENT_TRANSIT, AGENT_WAITING, AGENT_WAKING, doAction(), SIG_AGENT_ACTIVE, SIG_AGENT_DELETE, SIG_AGENT_SUSPEND, SIG_AGENT_TRANSIT, SIG_AGENT_WAIT, SIG_AGENT_WAKE, and this_agent.
Referenced by listener_extern_signals_Thread().
takeDown()
void gagent::Agent::takeDown () virtual
Definition at line 249 of file Agent.cpp.
Referenced by _init().
Member Data Documentation
AGENT_ACTIVE
const int gagent::Agent::AGENT_ACTIVE = 3 static
Definition at line 93 of file Agent.hpp.
Referenced by control_Thread(), doAction(), doActivate(), and signal_handler().
AGENT_CREATED
const int gagent::Agent::AGENT_CREATED = 1 static
Definition at line 91 of file Agent.hpp.
AGENT_DELETED
const int gagent::Agent::AGENT_DELETED = 7 static
Definition at line 97 of file Agent.hpp.
Referenced by control_Thread(), doAction(), doDelete(), and signal_handler().
AGENT_INITED
const int gagent::Agent::AGENT_INITED = 2 static
Definition at line 92 of file Agent.hpp.
Referenced by _init().
AGENT_SUSPENDED
const int gagent::Agent::AGENT_SUSPENDED = 4 static
Definition at line 94 of file Agent.hpp.
Referenced by control_Thread(), doAction(), doSuspend(), and signal_handler().
AGENT_TRANSIT
const int gagent::Agent::AGENT_TRANSIT = 5 static
Definition at line 95 of file Agent.hpp.
Referenced by control_Thread(), doAction(), doMove(), and signal_handler().
AGENT_UNKNOWN
const int gagent::Agent::AGENT_UNKNOWN = 0 static
Definition at line 90 of file Agent.hpp.
Referenced by _init().
AGENT_WAITING
const int gagent::Agent::AGENT_WAITING = 6 static
Definition at line 96 of file Agent.hpp.
Referenced by control_Thread(), doAction(), doWait(), and signal_handler().
AGENT_WAKING
const int gagent::Agent::AGENT_WAKING = 8 static
Definition at line 98 of file Agent.hpp.
Referenced by control_Thread(), doAction(), doWake(), and signal_handler().
agentStatus
int gagent::Agent::agentStatus
Definition at line 89 of file Agent.hpp.
Referenced by _init().
chldpid
pid_t gagent::Agent::chldpid
Definition at line 102 of file Agent.hpp.
Referenced by _init(), doAction(), and init().
ppid
pid_t gagent::Agent::ppid
Definition at line 103 of file Agent.hpp.
Referenced by init().
this_agent
Agent* gagent::Agent::this_agent
Definition at line 105 of file Agent.hpp.
Referenced by Agent(), doAction(), init(), listener_extern_signals_Thread(), myAgent::setup(), and signal_handler().
The documentation for this class was generated from the following files:
src_agent/Agent.hpp
src_agent/Agent.cpp