gAgent: gagent::Behaviour Class Reference
gagent::Behaviour Class Reference
#include <Behaviour.hpp>
Public Member Functions
Behaviour ()
Behaviour (Agent *)
virtual void action ()
virtual bool done ()
virtual void onStart ()
virtual void onEnd ()
virtual int doDelete ()
virtual int doActivate ()
virtual int doSuspend ()
virtual int doWait ()
virtual int doWake ()
virtual int doMove ()
int doAction (const int)
virtual ~Behaviour ()
Public Attributes
Agent * this_agent
Detailed Description
Definition at line 30 of file Behaviour.hpp.
Constructor & Destructor Documentation
Behaviour() [1/2]
gagent::Behaviour::Behaviour ()
Behaviour
Definition at line 14 of file Behaviour.cpp.
References this_agent.
Behaviour() [2/2]
gagent::Behaviour::Behaviour (Agent * ag)
Definition at line 18 of file Behaviour.cpp.
References this_agent.
~Behaviour()
gagent::Behaviour::~Behaviour () virtual
Definition at line 39 of file Behaviour.cpp.
Member Function Documentation
action()
void gagent::Behaviour::action () virtual
Reimplemented in gagent::OneShotBehaviour, gagent::CyclicBehaviour, gagent::WakerBehaviour, and gagent::TickerBehaviour.
Definition at line 23 of file Behaviour.cpp.
Referenced by gagent::Agent::exthread().
doAction()
int gagent::Behaviour::doAction (const int a)
Definition at line 66 of file Behaviour.cpp.
References gagent::Agent::doAction(), and this_agent.
doActivate()
int gagent::Behaviour::doActivate () virtual
Definition at line 47 of file Behaviour.cpp.
References gagent::Agent::doActivate(), and this_agent.
doDelete()
int gagent::Behaviour::doDelete () virtual
Definition at line 43 of file Behaviour.cpp.
References gagent::Agent::doDelete(), and this_agent.
doMove()
int gagent::Behaviour::doMove () virtual
Definition at line 63 of file Behaviour.cpp.
References gagent::Agent::doMove(), and this_agent.
done()
bool gagent::Behaviour::done () virtual
Reimplemented in gagent::OneShotBehaviour, gagent::CyclicBehaviour, gagent::WakerBehaviour, and gagent::TickerBehaviour.
Definition at line 27 of file Behaviour.cpp.
Referenced by gagent::Agent::exthread().
doSuspend()
int gagent::Behaviour::doSuspend () virtual
Definition at line 51 of file Behaviour.cpp.
References gagent::Agent::doSuspend(), and this_agent.
doWait()
int gagent::Behaviour::doWait () virtual
Definition at line 55 of file Behaviour.cpp.
References gagent::Agent::doWait(), and this_agent.
doWake()
int gagent::Behaviour::doWake () virtual
Definition at line 59 of file Behaviour.cpp.
References gagent::Agent::doWake(), and this_agent.
onEnd()
void gagent::Behaviour::onEnd () virtual
Definition at line 35 of file Behaviour.cpp.
Referenced by gagent::Agent::exthread().
onStart()
void gagent::Behaviour::onStart () virtual
Definition at line 31 of file Behaviour.cpp.
Referenced by gagent::Agent::exthread().
Member Data Documentation
this_agent
Agent* gagent::Behaviour::this_agent
Definition at line 50 of file Behaviour.hpp.
Referenced by Behaviour(), Behaviour(), doAction(), doActivate(), doDelete(), doMove(), doSuspend(), doWait(), doWake(), and myTickerBehaviour::onTick().
The documentation for this class was generated from the following files:
src_agent/Behaviour.hpp
src_agent/Behaviour.cpp