gAgent: gagent::UDPChannel Class Reference
gagent::UDPChannel Class Reference
UDP communication channel.
#include <CommunicationManager.hpp>
Classes
class Impl
Public Member Functions
UDPChannel (const std::string &address, int port)
~UDPChannel () override
bool send (const ACLMessage &message, const std::string &destination) override
Send a message.
bool receive (ACLMessage &message) override
Receive a message (non-blocking)
bool isActive () const override
Check if channel is active.
void close () override
Close the channel.
Public Member Functions inherited from gagent::CommunicationChannel
virtual ~CommunicationChannel ()=default
Detailed Description
UDP communication channel.
Definition at line 66 of file CommunicationManager.hpp.
Constructor & Destructor Documentation
UDPChannel()
gagent::UDPChannel::UDPChannel (const std::string & address, int port)
Definition at line 28 of file CommunicationManager.cpp.
References close(), and LOG_INFO.
~UDPChannel()
gagent::UDPChannel::~UDPChannel () override
Definition at line 58 of file CommunicationManager.cpp.
References close().
Member Function Documentation
close()
void gagent::UDPChannel::close () override virtual
Close the channel.
Implements gagent::CommunicationChannel.
Definition at line 119 of file CommunicationManager.cpp.
References close(), and LOG_INFO.
Referenced by close(), UDPChannel(), and ~UDPChannel().
isActive()
bool gagent::UDPChannel::isActive () const override virtual
Check if channel is active.
Implements gagent::CommunicationChannel.
Definition at line 115 of file CommunicationManager.cpp.
receive()
bool gagent::UDPChannel::receive (ACLMessage & message) override virtual
Receive a message (non-blocking)
Parameters
message Output parameter for received message
Returns
true if message received
Implements gagent::CommunicationChannel.
Definition at line 95 of file CommunicationManager.cpp.
References LOG_DEBUG.
send()
bool gagent::UDPChannel::send (const ACLMessage & message, const std::string & destination) override virtual
Send a message.
Parameters
message ACL message to send
destination Destination address
Returns
true if sent successfully
Implements gagent::CommunicationChannel.
Definition at line 62 of file CommunicationManager.cpp.
References LOG_ERROR.
The documentation for this class was generated from the following files:
src_agent/CommunicationManager.hpp
src_agent/CommunicationManager.cpp