gAgent: myEnv Class Reference
myEnv Class Reference
Public Member Functions
virtual void init_env ()
virtual void link_attribut ()
virtual void event_loop ()
Public Member Functions inherited from gagent::Environnement
Environnement ()
virtual ~Environnement ()
virtual void start (bool gui, unsigned int timer_val) final
virtual void clear_nsap () final
virtual int push_nsap () final
virtual int pull_nsap () final
virtual std::map< int, std::string > * get_nsaps () final
virtual void link_id (std::string _id) final
virtual void link_name (std::string _name) final
virtual void link_pos_x (std::string _pos_x) final
virtual void link_pos_y (std::string _pos_y) final
virtual void link_color (std::string _color) final
virtual void link_shape (std::string _shape) final
virtual void link_size (std::string _size) final
virtual void link_size_x (std::string _size_x) final
virtual void link_size_y (std::string _size_y) final
virtual void link_size_z (std::string _size_z) final
virtual void link_val (std::string _val) final
virtual void make_agent () final
virtual void readDataFromQueueMsg ()
int sendMsgMonitor (std::string)
Additional Inherited Members
Public Attributes inherited from gagent::Environnement
std::string id
std::string name
std::string shape
std::string size
std::string size_x
std::string size_y
std::string size_z
std::string color
std::string pos_x
std::string pos_y
std::string val
std::string pattern
std::vector< std::string > vals
std::vector< gagent::VisualAgent * > list_visual_agents
int map_width = 600
int map_height = 300
Detailed Description
Definition at line 12 of file main.cpp.
Member Function Documentation
event_loop()
virtual void myEnv::event_loop () inline virtual
Reimplemented from gagent::Environnement.
Definition at line 32 of file main.cpp.
init_env()
virtual void myEnv::init_env () inline virtual
Reimplemented from gagent::Environnement.
Definition at line 15 of file main.cpp.
link_attribut()
virtual void myEnv::link_attribut () inline virtual
Reimplemented from gagent::Environnement.
Definition at line 19 of file main.cpp.
References gagent::Environnement::link_color(), gagent::Environnement::link_id(), gagent::Environnement::link_name(), gagent::Environnement::link_pos_x(), gagent::Environnement::link_pos_y(), gagent::Environnement::link_shape(), gagent::Environnement::link_size(), gagent::Environnement::link_size_x(), gagent::Environnement::link_size_y(), and gagent::Environnement::link_size_z().
The documentation for this class was generated from the following file:
test_agent/main.cpp